/**
 * Precomputed Sample Chess Games with rich review metadata
 * Morphy vs. Duke of Brunswick & Count Isouard (The Opera Game, 1858)
 */

import { ChessGameSummary, ChessReviewItem } from './types';

export const OPERA_GAME_SUMMARY: ChessGameSummary = {
  id: 'game-opera-1858',
  title: 'Paul Morphy vs. Duke of Brunswick & Count Isouard',
  subtitle: 'The Opera Game • Paris, 1858',
  event: 'Paris Opera House',
  site: 'Paris FRA',
  date: '1858.??.??',
  round: '1',
  accuracyPercentage: 94.2,
  opponentAccuracyPercentage: 68.5,
  playerColor: 'white',
  whitePlayer: { name: 'Paul Morphy', rating: 2650, accuracy: 94.2 },
  blackPlayer: { name: 'Duke & Count', rating: 2100, accuracy: 68.5 },
  result: '1-0',
  pgn: `[Event "Paris Opera"]
[Site "Paris FRA"]
[Date "1858.??.??"]
[Round "1"]
[White "Morphy, Paul"]
[Black "Duke of Brunswick & Count Isouard"]
[Result "1-0"]

1. e4 e5 2. Nf3 d6 3. d4 Bg4 4. dxe5 Bxf3 5. Qxf3 dxe5 6. Bc4 Nf6 7. Qb3 Qe7 8. Nc3 c6 9. Bg5 b5 10. Nxb5 cxb5 11. Bxb5+ Nbd7 12. O-O-O Rd8 13. Rxd7 Rxd7 14. Rd1 Qe6 15. Bxd7+ Nxd7 16. Qb8+ Nxb8 17. Rd8# 1-0`,
  signalCounts: {
    best: 11,
    great: 4,
    good: 2,
    book: 3,
    inaccuracy: 2,
    mistake: 3,
    blunder: 2,
  },
  keyTakeaway: 'Rapid piece development and relentless initiative crush slow defensive play.',
};

export const OPERA_GAME_REVIEW_ITEMS: ChessReviewItem[] = [
  {
    id: 'move-1-w',
    stepIndex: 1,
    title: '1. e4',
    subtitle: 'White to move',
    signal: 'book',
    score: 0.3,
    scoreDelta: 0.0,
    explanation: 'Standard King\'s Pawn opening, controlling the center and opening lines for bishop and queen.',
    payload: {
      san: 'e4',
      moveNumber: 1,
      color: 'w',
      piece: 'p',
      from: 'e2',
      to: 'e4',
      fen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1',
      previousFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
      evalScore: 0.3,
    },
  },
  {
    id: 'move-1-b',
    stepIndex: 2,
    title: '1... e5',
    subtitle: 'Black to move',
    signal: 'book',
    score: 0.2,
    scoreDelta: 0.0,
    explanation: 'Symmetrical response, fighting directly for central space.',
    payload: {
      san: 'e5',
      moveNumber: 1,
      color: 'b',
      piece: 'p',
      from: 'e7',
      to: 'e5',
      fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2',
      previousFen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1',
      evalScore: 0.2,
    },
  },
  {
    id: 'move-2-w',
    stepIndex: 3,
    title: '2. Nf3',
    subtitle: 'White to move',
    signal: 'best',
    score: 0.4,
    scoreDelta: 0.2,
    explanation: 'Develops a knight toward the center while immediately attacking the e5-pawn.',
    payload: {
      san: 'Nf3',
      moveNumber: 2,
      color: 'w',
      piece: 'n',
      from: 'g1',
      to: 'f3',
      fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2',
      previousFen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2',
      evalScore: 0.4,
    },
  },
  {
    id: 'move-2-b',
    stepIndex: 4,
    title: '2... d6',
    subtitle: 'Black to move',
    signal: 'good',
    score: 0.1,
    scoreDelta: -0.3,
    explanation: 'Philidor Defense. Solidly protects e5, but cramps Black\'s dark-squared bishop.',
    bestAlternative: 'Nc6',
    payload: {
      san: 'd6',
      moveNumber: 2,
      color: 'b',
      piece: 'p',
      from: 'd7',
      to: 'd6',
      fen: 'rnbqkbnr/ppp2ppp/3p4/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3',
      previousFen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2',
      evalScore: 0.1,
      engineBestMove: 'Nc6',
    },
  },
  {
    id: 'move-3-w',
    stepIndex: 5,
    title: '3. d4',
    subtitle: 'White to move',
    signal: 'best',
    score: 0.7,
    scoreDelta: 0.6,
    explanation: 'Directly strikes at Black\'s central pawn structure, challenging the Philidor setup.',
    payload: {
      san: 'd4',
      moveNumber: 3,
      color: 'w',
      piece: 'p',
      from: 'd2',
      to: 'd4',
      fen: 'rnbqkbnr/ppp2ppp/3p4/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq d3 0 3',
      previousFen: 'rnbqkbnr/ppp2ppp/3p4/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3',
      evalScore: 0.7,
    },
  },
  {
    id: 'move-3-b',
    stepIndex: 6,
    title: '3... Bg4',
    subtitle: 'Black to move',
    signal: 'inaccuracy',
    score: 0.0,
    scoreDelta: -0.7,
    explanation: 'Pins the knight, but leads to losing the bishop pair early after White trades on e5.',
    bestAlternative: 'exd4',
    payload: {
      san: 'Bg4',
      moveNumber: 3,
      color: 'b',
      piece: 'b',
      from: 'c8',
      to: 'g4',
      fen: 'rn1qkbnr/ppp2ppp/3p4/4p3/3PP1b1/5N2/PPP2PPP/RNBQKB1R w KQkq - 1 4',
      previousFen: 'rnbqkbnr/ppp2ppp/3p4/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq d3 0 3',
      evalScore: 0.0,
      engineBestMove: 'exd4',
    },
  },
  {
    id: 'move-4-w',
    stepIndex: 7,
    title: '4. dxe5',
    subtitle: 'White to move',
    signal: 'best',
    score: 1.2,
    scoreDelta: 1.2,
    explanation: 'Forces Black to make a concession. Taking back on e5 loses a pawn or queen.',
    payload: {
      san: 'dxe5',
      moveNumber: 4,
      color: 'w',
      piece: 'p',
      from: 'd4',
      to: 'e5',
      captured: 'p',
      fen: 'rn1qkbnr/ppp2ppp/3p4/4P3/4P1b1/5N2/PPP2PPP/RNBQKB1R b KQkq - 0 4',
      previousFen: 'rn1qkbnr/ppp2ppp/3p4/4p3/3PP1b1/5N2/PPP2PPP/RNBQKB1R w KQkq - 1 4',
      evalScore: 1.2,
    },
  },
  {
    id: 'move-4-b',
    stepIndex: 8,
    title: '4... Bxf3',
    subtitle: 'Black to move',
    signal: 'good',
    score: 1.0,
    scoreDelta: -0.2,
    explanation: 'Forced response to avoid immediate tactic on f7 or e5.',
    payload: {
      san: 'Bxf3',
      moveNumber: 4,
      color: 'b',
      piece: 'b',
      from: 'g4',
      to: 'f3',
      captured: 'n',
      fen: 'rn1qkbnr/ppp2ppp/3p4/4P3/4P3/5b2/PPP2PPP/RNBQKB1R w KQkq - 0 5',
      previousFen: 'rn1qkbnr/ppp2ppp/3p4/4P3/4P1b1/5N2/PPP2PPP/RNBQKB1R b KQkq - 0 4',
      evalScore: 1.0,
    },
  },
  {
    id: 'move-5-w',
    stepIndex: 9,
    title: '5. Qxf3',
    subtitle: 'White to move',
    signal: 'best',
    score: 1.4,
    scoreDelta: 0.4,
    explanation: 'Recaptures with the queen, creating dangerous threats along the f7 diagonal.',
    payload: {
      san: 'Qxf3',
      moveNumber: 5,
      color: 'w',
      piece: 'q',
      from: 'd1',
      to: 'f3',
      captured: 'b',
      fen: 'rn1qkbnr/ppp2ppp/3p4/4P3/4P3/5Q2/PPP2PPP/RNB1KB1R b KQkq - 0 5',
      previousFen: 'rn1qkbnr/ppp2ppp/3p4/4P3/4P3/5b2/PPP2PPP/RNBQKB1R w KQkq - 0 5',
      evalScore: 1.4,
    },
  },
  {
    id: 'move-5-b',
    stepIndex: 10,
    title: '5... dxe5',
    subtitle: 'Black to move',
    signal: 'good',
    score: 1.2,
    scoreDelta: -0.2,
    explanation: 'Recaptures the central pawn.',
    payload: {
      san: 'dxe5',
      moveNumber: 5,
      color: 'b',
      piece: 'p',
      from: 'd6',
      to: 'e5',
      captured: 'p',
      fen: 'rn1qkbnr/ppp2ppp/8/4p3/4P3/5Q2/PPP2PPP/RNB1KB1R w KQkq - 0 6',
      previousFen: 'rn1qkbnr/ppp2ppp/3p4/4P3/4P3/5Q2/PPP2PPP/RNBQKB1R b KQkq - 0 5',
      evalScore: 1.2,
    },
  },
  {
    id: 'move-6-w',
    stepIndex: 11,
    title: '6. Bc4',
    subtitle: 'White to move',
    signal: 'best',
    score: 1.8,
    scoreDelta: 0.6,
    explanation: 'Develops the bishop to a powerful diagonal, threatening mate on f7.',
    payload: {
      san: 'Bc4',
      moveNumber: 6,
      color: 'w',
      piece: 'b',
      from: 'f1',
      to: 'c4',
      fen: 'rn1qkbnr/ppp2ppp/8/4p3/2B1P3/5Q2/PPP2PPP/RNB1K2R b KQkq - 1 6',
      previousFen: 'rn1qkbnr/ppp2ppp/8/4p3/4P3/5Q2/PPP2PPP/RNB1KB1R w KQkq - 0 6',
      evalScore: 1.8,
    },
  },
  {
    id: 'move-6-b',
    stepIndex: 12,
    title: '6... Nf6',
    subtitle: 'Black to move',
    signal: 'good',
    score: 1.6,
    scoreDelta: -0.2,
    explanation: 'Blocks the checkmate threat on f7 with a developing knight move.',
    payload: {
      san: 'Nf6',
      moveNumber: 6,
      color: 'b',
      piece: 'n',
      from: 'g8',
      to: 'f6',
      fen: 'rn1qkb1r/ppp2ppp/5n2/4p3/2B1P3/5Q2/PPP2PPP/RNB1K2R w KQkq - 2 7',
      previousFen: 'rn1qkbnr/ppp2ppp/8/4p3/2B1P3/5Q2/PPP2PPP/RNB1K2R b KQkq - 1 6',
      evalScore: 1.6,
    },
  },
  {
    id: 'move-7-w',
    stepIndex: 13,
    title: '7. Qb3',
    subtitle: 'White to move',
    signal: 'great',
    score: 2.5,
    scoreDelta: 0.9,
    explanation: 'Double attack! Threats on b7 and f7 simultaneously.',
    payload: {
      san: 'Qb3',
      moveNumber: 7,
      color: 'w',
      piece: 'q',
      from: 'f3',
      to: 'b3',
      fen: 'rn1qkb1r/ppp2ppp/5n2/4p3/2B1P3/1Q3N2/PPP2PPP/RNB1K2R b KQkq - 3 7',
      previousFen: 'rn1qkb1r/ppp2ppp/5n2/4p3/2B1P3/5Q2/PPP2PPP/RNB1K2R w KQkq - 2 7',
      evalScore: 2.5,
    },
  },
  {
    id: 'move-7-b',
    stepIndex: 14,
    title: '7... Qe7',
    subtitle: 'Black to move',
    signal: 'inaccuracy',
    score: 3.2,
    scoreDelta: -0.7,
    explanation: 'Defends f7, but blocks the dark-squared bishop and leaves b7 vulnerable.',
    bestAlternative: 'd5',
    payload: {
      san: 'Qe7',
      moveNumber: 7,
      color: 'b',
      piece: 'q',
      from: 'd8',
      to: 'e7',
      fen: 'rn2kb1r/ppp1qppp/5n2/4p3/2B1P3/1Q3N2/PPP2PPP/RNB1K2R w KQkq - 4 8',
      previousFen: 'rn1qkb1r/ppp2ppp/5n2/4p3/2B1P3/1Q3N2/PPP2PPP/RNB1K2R b KQkq - 3 7',
      evalScore: 3.2,
      engineBestMove: 'd5',
    },
  },
  {
    id: 'move-8-w',
    stepIndex: 15,
    title: '8. Nc3',
    subtitle: 'White to move',
    signal: 'great',
    score: 3.8,
    scoreDelta: 0.6,
    explanation: 'Morphy declines taking the b7 pawn immediately to prioritize total piece development!',
    payload: {
      san: 'Nc3',
      moveNumber: 8,
      color: 'w',
      piece: 'n',
      from: 'b1',
      to: 'c3',
      fen: 'rn2kb1r/ppp1qppp/5n2/4p3/2B1P3/1QN2N2/PPP2PPP/R1B1K2R b KQkq - 5 8',
      previousFen: 'rn2kb1r/ppp1qppp/5n2/4p3/2B1P3/1Q3N2/PPP2PPP/RNB1K2R w KQkq - 4 8',
      evalScore: 3.8,
    },
  },
  {
    id: 'move-8-b',
    stepIndex: 16,
    title: '8... c6',
    subtitle: 'Black to move',
    signal: 'mistake',
    score: 4.5,
    scoreDelta: -0.7,
    explanation: 'Defends b5, but loses another tempo while White is fully developed.',
    bestAlternative: 'Na6',
    payload: {
      san: 'c6',
      moveNumber: 8,
      color: 'b',
      piece: 'p',
      from: 'c7',
      to: 'c6',
      fen: 'rn2kb1r/pp2qppp/2p2n2/4p3/2B1P3/1QN2N2/PPP2PPP/R1B1K2R w KQkq - 0 9',
      previousFen: 'rn2kb1r/ppp1qppp/5n2/4p3/2B1P3/1QN2N2/PPP2PPP/R1B1K2R b KQkq - 5 8',
      evalScore: 4.5,
      engineBestMove: 'Na6',
    },
  },
  {
    id: 'move-9-w',
    stepIndex: 17,
    title: '9. Bg5',
    subtitle: 'White to move',
    signal: 'best',
    score: 5.2,
    scoreDelta: 0.7,
    explanation: 'Pins the knight on f6, increasing pressure on Black\'s cramped position.',
    payload: {
      san: 'Bg5',
      moveNumber: 9,
      color: 'w',
      piece: 'b',
      from: 'c1',
      to: 'g5',
      fen: 'rn2kb1r/pp2qppp/2p2n2/4p1B1/2B1P3/1QN5/PPP2PPP/R3K2R b KQkq - 1 9',
      previousFen: 'rn2kb1r/pp2qppp/2p2n2/4p3/2B1P3/1QN2N2/PPP2PPP/R1B1K2R w KQkq - 0 9',
      evalScore: 5.2,
    },
  },
  {
    id: 'move-9-b',
    stepIndex: 18,
    title: '9... b5',
    subtitle: 'Black to move',
    signal: 'blunder',
    score: 7.5,
    scoreDelta: -2.3,
    explanation: 'Tries to kick the bishop, but sets up a famous knight sacrifice!',
    bestAlternative: 'Na6',
    payload: {
      san: 'b5',
      moveNumber: 9,
      color: 'b',
      piece: 'p',
      from: 'b7',
      to: 'b5',
      fen: 'rn2kb1r/p3qppp/2p2n2/1p2p1B1/2B1P3/1QN5/PPP2PPP/R3K2R w KQkq b6 0 10',
      previousFen: 'rn2kb1r/pp2qppp/2p2n2/4p1B1/2B1P3/1QN5/PPP2PPP/R3K2R b KQkq - 1 9',
      evalScore: 7.5,
      engineBestMove: 'Na6',
    },
  },
  {
    id: 'move-10-w',
    stepIndex: 19,
    title: '10. Nxb5!',
    subtitle: 'White to move',
    signal: 'great',
    score: 8.4,
    scoreDelta: 0.9,
    explanation: 'Brilliant sacrifice! Morphy destroys Black\'s queenside pawn protection.',
    payload: {
      san: 'Nxb5',
      moveNumber: 10,
      color: 'w',
      piece: 'n',
      from: 'c3',
      to: 'b5',
      captured: 'p',
      fen: 'rn2kb1r/p3qppp/2p2n2/1N2p1B1/2B1P3/1Q6/PPP2PPP/R3K2R b KQkq - 0 10',
      previousFen: 'rn2kb1r/p3qppp/2p2n2/1p2p1B1/2B1P3/1QN5/PPP2PPP/R3K2R w KQkq b6 0 10',
      evalScore: 8.4,
    },
  },
  {
    id: 'move-10-b',
    stepIndex: 20,
    title: '10... cxb5',
    subtitle: 'Black to move',
    signal: 'good',
    score: 8.2,
    scoreDelta: 0.2,
    explanation: 'Accepting the knight, but opening the king to devastating attacks.',
    payload: {
      san: 'cxb5',
      moveNumber: 10,
      color: 'b',
      piece: 'p',
      from: 'c6',
      to: 'b5',
      captured: 'n',
      fen: 'rn2kb1r/p3qppp/5n2/1p2p1B1/2B1P3/1Q6/PPP2PPP/R3K2R w KQkq - 0 11',
      previousFen: 'rn2kb1r/p3qppp/2p2n2/1N2p1B1/2B1P3/1Q6/PPP2PPP/R3K2R b KQkq - 0 10',
      evalScore: 8.2,
    },
  },
  {
    id: 'move-11-w',
    stepIndex: 21,
    title: '11. Bxb5+',
    subtitle: 'White to move',
    signal: 'best',
    score: 9.0,
    scoreDelta: 0.8,
    explanation: 'Checks the king and maintains relentless initiative.',
    payload: {
      san: 'Bxb5+',
      moveNumber: 11,
      color: 'w',
      piece: 'b',
      from: 'c4',
      to: 'b5',
      captured: 'p',
      isCheck: true,
      fen: 'rn2kb1r/p3qppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/R3K2R b KQkq - 0 11',
      previousFen: 'rn2kb1r/p3qppp/5n2/1p2p1B1/2B1P3/1Q6/PPP2PPP/R3K2R w KQkq - 0 11',
      evalScore: 9.0,
    },
  },
  {
    id: 'move-11-b',
    stepIndex: 22,
    title: '11... Nbd7',
    subtitle: 'Black to move',
    signal: 'good',
    score: 8.8,
    scoreDelta: 0.2,
    explanation: 'Blocks the check, but both black knights are now pinned!',
    payload: {
      san: 'Nbd7',
      moveNumber: 11,
      color: 'b',
      piece: 'n',
      from: 'b8',
      to: 'd7',
      fen: 'r3kb1r/p2nqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/R3K2R w KQkq - 1 12',
      previousFen: 'rn2kb1r/p3qppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/R3K2R b KQkq - 0 11',
      evalScore: 8.8,
    },
  },
  {
    id: 'move-12-w',
    stepIndex: 23,
    title: '12. O-O-O',
    subtitle: 'White to move',
    signal: 'great',
    score: 11.5,
    scoreDelta: 2.7,
    explanation: 'Queenside castling brings the d1-rook into the attack instantly with full power!',
    payload: {
      san: 'O-O-O',
      moveNumber: 12,
      color: 'w',
      piece: 'k',
      from: 'e1',
      to: 'c1',
      fen: 'r3kb1r/p2nqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR3R b kq - 2 12',
      previousFen: 'r3kb1r/p2nqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/R3K2R w KQkq - 1 12',
      evalScore: 11.5,
    },
  },
  {
    id: 'move-12-b',
    stepIndex: 24,
    title: '12... Rd8',
    subtitle: 'Black to move',
    signal: 'mistake',
    score: 12.8,
    scoreDelta: -1.3,
    explanation: 'Desperate defensive move to support the pinned d7 knight.',
    bestAlternative: 'O-O-O',
    payload: {
      san: 'Rd8',
      moveNumber: 12,
      color: 'b',
      piece: 'r',
      from: 'a8',
      to: 'd8',
      fen: '3rkb1r/p2nqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR3R w k - 3 13',
      previousFen: 'r3kb1r/p2nqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR3R b kq - 2 12',
      evalScore: 12.8,
      engineBestMove: 'O-O-O',
    },
  },
  {
    id: 'move-13-w',
    stepIndex: 25,
    title: '13. Rxd7!',
    subtitle: 'White to move',
    signal: 'great',
    score: 14.5,
    scoreDelta: 1.7,
    explanation: 'Rook exchange sacrifice! Removes Black\'s key defender.',
    payload: {
      san: 'Rxd7',
      moveNumber: 13,
      color: 'w',
      piece: 'r',
      from: 'd1',
      to: 'd7',
      captured: 'n',
      fen: '3rkb1r/p2Rqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2K4R b k - 0 13',
      previousFen: '3rkb1r/p2nqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR3R w k - 3 13',
      evalScore: 14.5,
    },
  },
  {
    id: 'move-13-b',
    stepIndex: 26,
    title: '13... Rxd7',
    subtitle: 'Black to move',
    signal: 'good',
    score: 14.2,
    scoreDelta: 0.3,
    explanation: 'Recaptures the rook.',
    payload: {
      san: 'Rxd7',
      moveNumber: 13,
      color: 'b',
      piece: 'r',
      from: 'd8',
      to: 'd7',
      captured: 'r',
      fen: '4kb1r/p2rqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2K4R w k - 0 14',
      previousFen: '3rkb1r/p2Rqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2K4R b k - 0 13',
      evalScore: 14.2,
    },
  },
  {
    id: 'move-14-w',
    stepIndex: 27,
    title: '14. Rd1',
    subtitle: 'White to move',
    signal: 'best',
    score: 16.0,
    scoreDelta: 1.8,
    explanation: 'Brings the remaining rook into the open d-file with crushing force.',
    payload: {
      san: 'Rd1',
      moveNumber: 14,
      color: 'w',
      piece: 'r',
      from: 'h1',
      to: 'd1',
      fen: '4kb1r/p2rqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR4 b k - 1 14',
      previousFen: '4kb1r/p2rqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2K4R w k - 0 14',
      evalScore: 16.0,
    },
  },
  {
    id: 'move-14-b',
    stepIndex: 28,
    title: '14... Qe6',
    subtitle: 'Black to move',
    signal: 'blunder',
    score: 99.0,
    scoreDelta: -83.0,
    explanation: 'Offers queen trade, but allows a legendary forced checkmate sequence!',
    bestAlternative: 'Qd6',
    payload: {
      san: 'Qe6',
      moveNumber: 14,
      color: 'b',
      piece: 'q',
      from: 'e7',
      to: 'e6',
      fen: '4kb1r/p2r1ppp/4qn2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 2 15',
      previousFen: '4kb1r/p2rqppp/5n2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR4 b k - 1 14',
      evalScore: 99.0,
      engineBestMove: 'Qd6',
    },
  },
  {
    id: 'move-15-w',
    stepIndex: 29,
    title: '15. Bxd7+',
    subtitle: 'White to move',
    signal: 'best',
    score: 99.0,
    scoreDelta: 0.0,
    explanation: 'Removes the rook with check.',
    payload: {
      san: 'Bxd7+',
      moveNumber: 15,
      color: 'w',
      piece: 'b',
      from: 'b5',
      to: 'd7',
      captured: 'r',
      isCheck: true,
      fen: '4kb1r/p2B1ppp/4qn2/4p1B1/4P3/1Q6/PPP2PPP/2KR4 b k - 0 15',
      previousFen: '4kb1r/p2r1ppp/4qn2/1B2p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 2 15',
      evalScore: 99.0,
    },
  },
  {
    id: 'move-15-b',
    stepIndex: 30,
    title: '15... Nxd7',
    subtitle: 'Black to move',
    signal: 'good',
    score: 99.0,
    scoreDelta: 0.0,
    explanation: 'Recaptures with the knight.',
    payload: {
      san: 'Nxd7',
      moveNumber: 15,
      color: 'b',
      piece: 'n',
      from: 'f6',
      to: 'd7',
      captured: 'b',
      fen: '4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16',
      previousFen: '4kb1r/p2B1ppp/4qn2/4p1B1/4P3/1Q6/PPP2PPP/2KR4 b k - 0 15',
      evalScore: 99.0,
    },
  },
  {
    id: 'move-16-w',
    stepIndex: 31,
    title: '16. Qb8+!!',
    subtitle: 'White to move',
    signal: 'great',
    score: 99.0,
    scoreDelta: 0.0,
    explanation: 'QUEEN SACRIFICE! Deflects the defender of d8.',
    payload: {
      san: 'Qb8+',
      moveNumber: 16,
      color: 'w',
      piece: 'q',
      from: 'b3',
      to: 'b8',
      isCheck: true,
      fen: '1Q2kb1r/p2n1ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 b k - 1 16',
      previousFen: '4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16',
      evalScore: 99.0,
    },
  },
  {
    id: 'move-16-b',
    stepIndex: 32,
    title: '16... Nxb8',
    subtitle: 'Black to move',
    signal: 'good',
    score: 99.0,
    scoreDelta: 0.0,
    explanation: 'Forced recapture.',
    payload: {
      san: 'Nxb8',
      moveNumber: 16,
      color: 'b',
      piece: 'n',
      from: 'd7',
      to: 'b8',
      captured: 'q',
      fen: '1n2kb1r/p4ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 w k - 0 17',
      previousFen: '1Q2kb1r/p2n1ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 b k - 1 16',
      evalScore: 99.0,
    },
  },
  {
    id: 'move-17-w',
    stepIndex: 33,
    title: '17. Rd8#',
    subtitle: 'White to move',
    signal: 'best',
    score: 99.0,
    scoreDelta: 0.0,
    explanation: 'CHECKMATE! The rook delivers mate on d8 supported by the bishop on g5. Pure perfection.',
    payload: {
      san: 'Rd8#',
      moveNumber: 17,
      color: 'w',
      piece: 'r',
      from: 'd1',
      to: 'd8',
      isCheckmate: true,
      fen: '1n1Rkb1r/p4ppp/4q3/4p1B1/4P3/8/PPP2PPP/2K5 b k - 1 17',
      previousFen: '1n2kb1r/p4ppp/4q3/4p1B1/4P3/8/PPP2PPP/2KR4 w k - 0 17',
      evalScore: 99.0,
    },
  },
];
