import { EvaluationSignal, EvaluationSignalMeta } from './types';

export const EVALUATION_SIGNALS: Record<EvaluationSignal, EvaluationSignalMeta> = {
  best: {
    signal: 'best',
    label: 'Best Move',
    color: '#96bc4b',
    badgeBg: 'bg-emerald-500/15 border-emerald-500/30',
    badgeText: 'text-emerald-400 font-semibold',
    icon: 'CheckCircle2',
    severity: 0,
  },
  great: {
    signal: 'great',
    label: 'Great Move',
    color: '#5c8bb0',
    badgeBg: 'bg-blue-500/15 border-blue-500/30',
    badgeText: 'text-blue-400 font-semibold',
    icon: 'Sparkles',
    severity: 0,
  },
  good: {
    signal: 'good',
    label: 'Good Move',
    color: '#96bc4b',
    badgeBg: 'bg-emerald-500/10 border-emerald-500/20',
    badgeText: 'text-emerald-300',
    icon: 'Check',
    severity: 1,
  },
  book: {
    signal: 'book',
    label: 'Book Move',
    color: '#a88b60',
    badgeBg: 'bg-amber-700/15 border-amber-600/30',
    badgeText: 'text-amber-400 font-semibold',
    icon: 'BookOpen',
    severity: 0,
  },
  inaccuracy: {
    signal: 'inaccuracy',
    label: 'Inaccuracy',
    color: '#f0c15c',
    badgeBg: 'bg-yellow-500/15 border-yellow-500/30',
    badgeText: 'text-yellow-400 font-semibold',
    icon: 'HelpCircle',
    severity: 2,
  },
  mistake: {
    signal: 'mistake',
    label: 'Mistake',
    color: '#e58f2a',
    badgeBg: 'bg-orange-500/15 border-orange-500/30',
    badgeText: 'text-orange-400 font-semibold',
    icon: 'AlertTriangle',
    severity: 3,
  },
  blunder: {
    signal: 'blunder',
    label: 'Blunder',
    color: '#ca3431',
    badgeBg: 'bg-red-500/15 border-red-500/30',
    badgeText: 'text-red-400 font-semibold',
    icon: 'XCircle',
    severity: 4,
  },
};
